server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: com.lgd.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#spring的配置
spring:
  application:
    name : springcloud-provider-dept
  datasource :
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class -name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-test?useUnicode=true&characterEncoding=utf-8
    username : root
    password: 1328910

# Eureka配置：配置服务注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001
#    设定为true就可以显示出ip
    prefer-ip-address: true

info:
  app.name: lgd's provider 8001
  company.name: zust's imais

# 开启降级feign.hystrix
feign:
  hystrix:
    enabled: true